# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Each version creation
  create:
    tags:
      - v*
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Install Dependencies
      - name: Install aws-iam-authenticator
        run: |
          echo Installing aws-iam-authenticator...
          mkdir ~/aws
          curl -o ~/aws/aws-iam-authenticator \
          "https://amazon-eks.s3.us-west-2.amazonaws.com/\
          1.16.8/2020-04-16/bin/linux/amd64/aws-iam-authenticator"
          chmod +x ~/aws/aws-iam-authenticator
          sudo cp ~/aws/aws-iam-authenticator /usr/local/bin/aws-iam-authenticator
      # Apply Opentofu
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.0
      - name: Tofu fmt
        run: tofu fmt
      - name: Tofu init
        run: tofu init
      - name: Tofu validate
        run: tofu validate
      - name: Tofu Plan
        run: tofu plan
      - name: Tofu apply
        run : tofu apply -no-color --auto-approve

      # Publish assets
      - name: Upload kubeconfig
        uses: actions/upload-artifact@v4
        with: 
          name: kubeconfig
          path: kubeconfig
        
